#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="../../third_party/qt-plugins/$(uname -m)"
export QT_DBL_CLICK_DIST=150
export SCALE="0.9"
exec ./_ui
